PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?sub ?type ?typelabel
{ 
  ?sub a owl:NamedIndividual ;
    rdf:type ?type .
  optional { ?sub rdfs:label ?label . }
  ?type rdfs:label ?typelabel .
}
