# Workflow for MRIO Testing

name: MRIO Test

on:
  push:
  pull_request:

jobs:
  mrio_test:

    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.2

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          cd src/ontology && make test
