# Workflow for OBI Testing

name: MRIO Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mrio_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          cd src/ontology && make test