# Workflow for MRIO Testing

name: MRIO Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mrio_test:

    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.27

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          cd src/ontology && ls && make test
